### PR TITLE
Add: Page for /courses for All Courses

### PR DESCRIPTION
**Pull request by firefinchdev**

### CODE REVIEW

**Comment by firefinchdev** [comment]
@abhishek97 
Solved #5 
Pls Review

**Comment by abhishek97** [comment]
add screenshots

**Comment by firefinchdev** [comment]
screenshot from 2018-08-03 03-33-44
screenshot from 2018-08-03 03-34-49
screenshot from 2018-08-03 03-35-43

**Comment by firefinchdev** [comment]
@abhishek97 
Do tell me if you want some more changes.

**Comment by firefinchdev** [comment]
@abhishek97 
Any updates?

**Comment by firefinchdev** [comment]
screenshot from 2018-08-07 12-33-08
screenshot from 2018-08-07 12-33-17
@abhishek97 
Updated UI.
Pls review.

**Pull request merged**
